### ISSUE TITLE
oval:ssg-accounts_tmout failed to resolve

### ISSUE THREAD

**Issue by blueclouds055** [isimluk/openscap-portal#215]
OS: 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux (Linux Mint)

Scan command used:
oscap oval eval --verbose DEVEL --verbose-log-file acct.log --id oval:ssg-accounts_tmout:def:1 --results oval-res2.xml --report rep-oval2.html $OSCAP_DS/ssg-ubuntu2204-oval.xml

[acct.log](https://github.com/OpenSCAP/website/files/13251389/acct.log)

The log shows that it is reading TMOUT value but at the end I see the below error
Definition oval:ssg-accounts_tmout:def:1: error

/etc/profile has below line and /etc/profile.d/tmout.sh
TMOUT=3600
readonly TMOUT export TMOUT

$ oscap --version
OpenSCAP command line tool (oscap) 1.2.17
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1

==== Capabilities added by auto-loaded plugins ====
SCE Version: 1.0 (from libopenscap_sce.so.8)

**Comment by matejak** [comment]
You are using a very outdated version of the scanner, so it is very likely that nobody will help you.
Moreover, this is the OpenSCAP website repository, while you have an issue with the scanner, or with the content.
I close this because of this wrong repository, and I recommend you to use a newer scanner and possibly [oscap-report](https://github.com/OpenSCAP/openscap-report) for better overview of the results.
